### ISSUE TITLE
Roles and Permissions in MS Teams

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#1]
Understand the roles and permissions in MS Teams

---
- [x] #11
- [ ] Create a List of all Roles
  - [ ] list their permissions
  - [ ] sort them by permissions
- [ ] If Roles are missing add them
- [ ] Think about grouping Roles

---
[Wiki](https://github.com/XU-SE22-WS21-22/user-roles-and-permissions/wiki/Roles-and-Permissions)

**Comment by justTil** [comment]
Had no access
