### ISSUE TITLE
Request organigram and acces from XU

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#11]

**Comment by Viktoria-dot** [comment]
Organization chart request sent by mail to Gottfried on 06.12.2021

**Comment by Schati** [comment]
Request a meeting with Gottfried to clarify:

- [ ] Can he create an App in Azure for us?

- [ ] We need a Organigram

**Comment by justTil** [comment]
No response, created independent test environment
