### ISSUE TITLE
Mirror Roles and Permissions to Java

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#2]
Think of a way to mirror roles and permissions into Java

---
- [x] How to save roles
- [x] how to apply permissions

---
[Wiki](https://github.com/XU-SE22-WS21-22/user-roles-and-permissions/wiki/Roles-and-Permissions-Java-implementation)

**Comment by Schati** [comment]
- Team created a permission table in excel called [Permission_Table.xlsx](https://xuuniversity.sharepoint.com/:x:/s/XU-SE22-ProjectConfigurationandImplementation2021-SE-2.2-Group-03/EaQkjwU32IFFq1LqktPUbnUBepaCxufVgCRHi1jQ827rXg?e=HOxqqt&isSPOFile=1)
 -> Designing Table Structure

**Comment by justTil** [comment]
Created excel sheet with tables
