### ISSUE TITLE
Roles and Permissions for the Tool

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#3]
Think about Roles and Permissions for our tool

---
- [x] Make a list of all Roles we need
  - [x] Write down all the permissions
  - [x] Sort them by permissions
  - [x] Link them to MS Teams Roles

---
[Wiki](https://github.com/XU-SE22-WS21-22/user-roles-and-permissions/wiki/Roles-and-Permissions)

**Comment by justTil** [comment]
Permissions are out of scope since they are managed by the admins in Azure AD
