### ISSUE TITLE
Initial instruction for Database Team

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#7]
give the Database-Team Initial instruction for what we need and they have todo

[Message for Hendrik](https://teams.microsoft.com/l/message/19:hvW1DA_fYh8-SeEicy2jVez8lbXWJ5OLsW7fxzknwVk1@thread.tacv2/1638373516397?tenantId=964f9745-bd07-4d1d-9a24-40f9bc141cc4&groupId=d034e937-2b90-4c3d-bd33-8569061af165&parentMessageId=1638373516397&teamName=XU%20-%20SE2%2F2%20-%20Project%20Configuration%20and%20Implementation%202021&channelName=Allgemein&createdTime=1638373516397)

**Comment by justTil** [comment]
Gave instructions
