### ISSUE TITLE
Get information from Dashboard Team

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#8]
Get information from Dashboard Team about what users/roles can see and do in the dashboard

---
- [x] Get a list of all available elements / actions for the dashboard
- [x] Distribute permissions to elements / action
- [x] Set permission for cirant roles

---
[Wiki](https://github.com/XU-SE22-WS21-22/user-roles-and-permissions/wiki/Roles-and-Permissions)

**Comment by Viktoria-dot** [comment]
List requested from Team FiveUnicorns (Management Dashboard Team) - Team Chat form December 4th - Waiting for response

**Comment by Himyu** [comment]
Why Teamchst when we use Teams?

**Comment by Viktoria-dot** [comment]
**List Management Dashboard** 
- Brief overview of List of Lecturers with status light 
- Management ToDos: Tasks for the ministry 
- Monthly summary of reports with green status
- KPI's

**Lecturer Dashboard**
- Reporting Graph with status
- Score/ Gamification 
- Hand-In deadlines
- Overview/ List of last activities (for exp. Podcasts, Papers etc)
