### ISSUE TITLE
Research Login with MS Teams

### ISSUE THREAD

**Issue by Himyu** [XU-SE22-WS21-22/user-roles-and-permissions#9]
Research a method to login with MS Teams

---
- [x] Research method to implement MS Teams
  - [x] Login
  - [x] User information
  - [x] Logout
 
---
[Wiki](https://github.com/XU-SE22-WS21-22/user-roles-and-permissions/wiki/Login-with-MS-Teams)

**Comment by justTil** [comment]
Decided to use MS login, good documentation and up-to-date
